[package]
name = "normal-bitmap"
version = "0.1.0"
edition = "2021"
authors = ["Evie"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
image = "0.24.7"
